version: '3.8'

services:
  logsift-cluster-1:
    build:
      context: ./submissions/notebox/environment
      dockerfile: Dockerfile
    container_name: logsift-cluster-1
    ports:
      - "2221:22"
    environment:
      - SSH_PASSWORD=password
      - SSH_PORT=22
    networks:
      - logsift-cluster-net

  logsift-cluster-2:
    build:
      context: ./submissions/notebox/environment
      dockerfile: Dockerfile
    container_name: logsift-cluster-2
    ports:
      - "2222:22"
    environment:
      - SSH_PASSWORD=password
      - SSH_PORT=22
    networks:
      - logsift-cluster-net

  logsift-cluster-3:
    build:
      context: ./submissions/notebox/environment
      dockerfile: Dockerfile
    container_name: logsift-cluster-3
    ports:
      - "2223:22"
    environment:
      - SSH_PASSWORD=password
      - SSH_PORT=22
    networks:
      - logsift-cluster-net

  logsift-cluster-4:
    build:
      context: ./submissions/notebox/environment
      dockerfile: Dockerfile
    container_name: logsift-cluster-4
    ports:
      - "2224:22"
    environment:
      - SSH_PASSWORD=password
      - SSH_PORT=22
    networks:
      - logsift-cluster-net

  logsift-cluster-5:
    build:
      context: ./submissions/notebox/environment
      dockerfile: Dockerfile
    container_name: logsift-cluster-5
    ports:
      - "2225:22"
    environment:
      - SSH_PASSWORD=password
      - SSH_PORT=22
    networks:
      - logsift-cluster-net

networks:
  logsift-cluster-net:
    driver: bridge
